# Generated by Django 3.1 on 2020-10-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=70)),
                ('link', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('time', models.CharField(max_length=70)),
            ],
        ),
    ]
